import { readFile, writeFile, access } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { join, resolve, dirname } from "node:path";
import { Script } from "node:vm";

// No dependencies, network requests or Flutter build are needed.
const directory = dirname(fileURLToPath(import.meta.url));
const root = resolve(directory, "../..");
const read = (path) => readFile(join(directory, path), "utf8");
const [
  renderer,
  flows,
  runtime,
  samples,
  icons,
  palette,
  logo,
  qr,
  router,
  catalog,
] = await Promise.all([
  read("renderer.js"),
  read("flows.js"),
  read("runtime.js"),
  read("sample-data.json").then(JSON.parse),
  read("assets/icons.json").then(JSON.parse),
  readFile(join(root, "lib/core/theme/app_colors.dart"), "utf8"),
  readFile(join(root, "assets/images/logo_corevent_full.png")),
  read("assets/qr-example.svg"),
  readFile(join(root, "lib/app/router.dart"), "utf8"),
  read("screen-catalog.json").then(JSON.parse),
]);
const colors = Object.fromEntries(
  [
    ...palette.matchAll(/static const (\w+) = Color\(0xFF([0-9A-Fa-f]{6})\);/g),
  ].map((match) => [match[1], match[2]]),
);
if (Object.keys(colors).length !== 12) {
  throw new Error("A paleta mudou. Revise os tokens do plugin antes de gerar.");
}
if (samples.events.length !== 2) {
  throw new Error("Informe dois eventos ilustrativos em sample-data.json.");
}
for (const event of samples.events) {
  for (const field of ["Title", "Category", "Date", "Location", "Rating"]) {
    if (typeof event[field] !== "string" || !event[field].trim()) {
      throw new Error(`Campo de evento inválido: ${field}`);
    }
  }
}
for (const [name, svg] of Object.entries(icons)) {
  if (!svg.includes("<svg") || !svg.includes("viewBox")) {
    throw new Error(`SVG inválido: ${name}`);
  }
}
if (
  logo.readUInt32BE(0) !== 0x89504e47 ||
  !qr.includes("<svg") ||
  !qr.includes("viewBox")
) {
  throw new Error("Logo PNG ou QR SVG inválido.");
}
const routes = [...router.matchAll(/path:\s*'([^']+)'/g)]
  .map((match) => match[1])
  .filter((route) => route !== "/design-system");
// Keep the plugin tied to the actual presentation files without reading API data.
const sourceFiles = [
  "auth/presentation/authenticated_page",
  "auth/presentation/login_page",
  "auth/presentation/register_page",
  "auth/presentation/verification_page",
  "auth/presentation/forgot_password_page",
  "auth/presentation/reset_password_page",
  "welcome/presentation/welcome_page",
  "home/presentation/home_page",
  "explore/presentation/explore_page",
  "tickets/presentation/tickets_page",
  "tickets/presentation/ticket_detail_sheet",
  "tickets/presentation/ticket_qr_page",
  "events/presentation/event_preview_sheet",
  "checkout/presentation/checkout_page",
  "checkout/presentation/order_status_page",
  "profile/presentation/profile_page",
  "profile/presentation/activity_pages",
  "profile/presentation/profile_details_page",
  "profile/presentation/avatar_editor_page",
  "profile/presentation/profile_form_pages",
  "favorites/presentation/favorites_page",
  "ratings/presentation/ratings_page",
  "ratings/presentation/rating_widgets",
];
await Promise.all(
  sourceFiles.map((source) =>
    access(join(root, "lib/features", source + ".dart")),
  ),
);
if (new Set(catalog.map((view) => view.name)).size !== catalog.length)
  throw new Error("Nomes repetidos no catálogo.");
for (const route of routes) {
  if (!catalog.some((view) => view.route === route))
    throw new Error("Rota sem mockup no catálogo: " + route);
}
await Promise.all(catalog.map((view) => access(join(root, view.source))));
const photos = await Promise.all(
  [0, 1].map(async (index) => {
    const bytes = await readFile(join(directory, `assets/event-${index}.jpg`));
    if (bytes[0] !== 0xff || bytes[1] !== 0xd8)
      throw new Error("Banner JPEG inválido.");
    return bytes.toString("base64");
  }),
);
const bundle = [
  "// Generated by build.mjs. Edit renderer.js, runtime.js and sample-data.json.",
  '"use strict";',
  `const MOCKUP_DATA = ${JSON.stringify({ ...samples, colors, routes, catalog })};`,
  `const MOCKUP_ASSETS = ${JSON.stringify({ icons, photos, logo: logo.toString("base64"), logoRatio: logo.readUInt32BE(16) / logo.readUInt32BE(20), qr })};`,
  runtime,
  flows,
  renderer,
].join("\n\n");
new Script(bundle, { filename: "code.js" });
await writeFile(join(directory, "code.js"), `${bundle}\n`);
console.log(`Plugin pronto: ${directory}`);
console.log(
  `${Object.keys(icons).length} ícones, 2 banners, logo e QR ilustrativo, 12 cores, ${routes.length} rotas públicas. JavaScript validado.`,
);
